### ISSUE TITLE
Support for the latest SEPA specifications

### ISSUE THREAD

**Issue by HWWyes** [AbcAeffchen/Sephpa#10]
According to the latest (German) [official documentation](https://www.firmenkunden.commerzbank.de/portal/media/corporatebanking/hauptportal/downloads-pop-up/sepa/Anlage_3_Datenformate_V30.pdf), the most recent PAIN versions are indeed pain.001.001.03 for Credit Transfer and pain.008.001.02 for Direct Debit. These are valid since November 20th, 2016. They feature even more simplifications than the former PAIN versions. The versions pain.001.003.03 and pain.008.003.02 remain valid, but are outdated.

I want to set up a new project using PHP with the latest SEPA support. At the moment being, my old project is made up as a VBA project in MS Access, and I am using the latest PAIN versions there. I wonder if there are plans to add the new versions to this library. I could perhaps try and make them up on my own, but I'm new to GitHub and do not know how to contribute without disturbing the original workflow.

**Comment by AbcAeffchen** [comment]
Hi, they are already supported in the develop branch. I hope I can release version 2 soon.
I think you can use this branch if you don't the new documentaion files which will come with version 2.

**Comment by HWWyes** [comment]
As I pointed out, I'm new to GitHub. How can I acces the development branch? Is there an appropriate composer tag?

**Comment by AbcAeffchen** [comment]
You can swtich to the develop branch on the main site of the repository.

I never tested this with composer but maybe this helps you:
https://lornajane.net/posts/2014/use-a-github-branch-as-a-composer-dependency

**Comment by HWWyes** [comment]
Thanks a lot. I can now use the develop branch with the most recent PAIN versions. The tip about the GitHub branch as a composer dependency works very wel. Now waiting for the official release of version 2.0.

**Comment by fabio-a-beretta** [comment]
Good afternoon. Waiting as well the latest PAIN.008.001.02 required by the French Bank System. Will use the dev branch for the moment. Hopefully rev 2 will come soon.

ty
f

**Comment by AbcAeffchen** [comment]
Hi,
I'm very sorry that it takes so long. I'm on this and it is on its way. 

Best,
Alex

**Comment by fabio-a-beretta** [comment]
Good afternoon Alex,

any update on availability of the 2.0 version. I still run on dev branch.

Thank in advance,
Fabio

**Comment by AbcAeffchen** [comment]
Hi Fabio,

I think most is finished. I still need to test a little bit, write a migration guide and check if the changelog contains everything relevant, especially the incompatibilities. 

Best,
Alex

**Comment by AbcAeffchen** [comment]
pain.008.001.02 is now supported with Sephpa 2.0.
