### ISSUE TITLE
Tag a new release

### ISSUE THREAD

**Issue by victorlap** [AbcAeffchen/Sephpa#11]
Hello Can you please tag a new release? I really want to use the 008.001.002 pain version but the newest release of this moment (1.3.0) does not provide this pain. I saw you added it to master, but haven't tagged a release since?

**Comment by AbcAeffchen** [comment]
Hi,

I still need to finish one last feature before I can release version 2.0.0
But you can use the development branch until then.

**Comment by victorlap** [comment]
Okay thanks!

Any idea when you are going to release version 2 and what the breaking changes are?

**Comment by AbcAeffchen** [comment]
you can look into the changelog in the development branch for the changes.

I don't know how long it will take, but I try to finish this as soon as possible.

**Comment by fabio-a-beretta** [comment]
Hello. I need as well the new release to support PAIN.008.001.02.

I have added the dev-master version to composer but I would use the stable release as soon as available.

ty
f

**Comment by AbcAeffchen** [comment]
Version 2.0 will be tagged tomorrow.
