### ISSUE TITLE
Import of a Sepa-File

### ISSUE THREAD

**Issue by dennobaby** [AbcAeffchen/Sephpa#15]
The core-point of this project is the creation of a sepa-file. 

Would it be possible and meaningfull to integrate a file-READER?

**Comment by AbcAeffchen** [comment]
I thought about this. currently there is not much of a point to do this. But the next version will be able to generate human readable pdf files that show what the sepa file contains.

Do you have use for a sepa file reader and what is it if I may ask?

**Comment by dennobaby** [comment]
A possible usecase would be the following: My App would create a SEPA-File with help of your library. At the moment, i save all information in my database to look at it at later time. If i could just read out the sepa-file, there would be no need to save theses informations a second time in the database. 
The second usecase i thought of would be to just manipulate a sepa-file. Change payment-Informations, ...

**Comment by AbcAeffchen** [comment]
Ok. I will look into this. I think it will not be part of Sephpa, but maybe an extra library.
But it will take a while and I cannot promise anything. And Sephpa 2.0 has definitely to be done first.

**Comment by spacie2136** [comment]
Hi, im also looking for importing my SEPA files back into my database.

**Comment by AbcAeffchen** [comment]
I think this is better placed in a separate project. But currently I find no time for this.
