### ISSUE TITLE
My bank requires Id in InitgPty

### ISSUE THREAD

**Issue by spacie2136** [AbcAeffchen/Sephpa#17]
I just tried to upload a Direct debit 008.001.02 file to my bank. It is the format required by my bank.
But i had to add some data at the header of the xml file to be acepted by my bank. (Cajamar Spain)

The data i added is the Id Tag inside InitgPty.

Is there a solution for this?

    <GrpHdr>
      <MsgId>MessageID-1235</MsgId>
      <CreDtTm>2018-09-12T17:15:26</CreDtTm>
      <NbOfTxs>1</NbOfTxs>
      <CtrlSum>2.34</CtrlSum>
      <InitgPty>
        <Nm>MY COMPANY NAME</Nm>
        <Id>
          <PrvtId>
            <Othr>
              <Id>ES43000MYCOMPANYID</Id>
              <SchmeNm>
                <Prtry>SEPA</Prtry>
              </SchmeNm>
            </Othr>
          </PrvtId>
        </Id>
      </InitgPty>
    </GrpHdr>

**Comment by AbcAeffchen** [comment]
I think it is currently not supported as it is recommended not to use this tag. 

I will try to add support for this for the next update.

**Comment by spacie2136** [comment]
Thank you very much! Dankeschön!

**Comment by AbcAeffchen** [comment]
I need to warn you. I'm very busy currently. So it will take a while. Same as with version 2.0 which I should lift to a full release.

**Comment by spacie2136** [comment]
Ok. I will have a look my self. Maybe i can solve it by myself. Im already looking for the get prop. function to get paymentCollection->debitInfo['ic'] in Sephpa.php.

Thanks anyway

**Comment by AbcAeffchen** [comment]
If you want to implement something, please make sure to use the 2.0 pre-release. Tthe interface changed a little bit.
