### ISSUE TITLE
Give the php acces to generate Xml

### ISSUE THREAD

**Issue by jmbIFR** [AbcAeffchen/Sephpa#21]
Make the generateXml() function public allow a direct access to php to the generated xml wihtout using the store or download function

https://github.com/AbcAeffchen/Sephpa/commit/5e3433e8cd210417060b66aee70a9ae8ba6f4802

**Comment by AbcAeffchen** [comment]
I'm not sure why Sephpa should support this. The only reason I can think about is that one uses Sephpa in some kind of commandline tool that should outputs the XML string to stdout which is piped into a file or something like that. But this seems not a very likely case.

Do you have an other reason for that?

**Comment by AbcAeffchen** [comment]
The function `Sephpa::generateOutput` returns an array of pairs of filename and a string representing the content of the file. For all xml files this is just xml code. So if one really needs to do something with this just parse the string. But it seems to invalidate the whole validation process that Sephpa does if one changes the file after it was created. So I will not provide a xml object out of the box.
