### ISSUE TITLE
Formated xml output

### ISSUE THREAD

**Issue by jmbIFR** [AbcAeffchen/Sephpa#22]
The generated xml is not formated.

The commit https://github.com/AbcAeffchen/Sephpa/commit/1029ca01a0e2c27b34fd6bb218ccd478140fd290 Allow to get a formatted XML output.

The array key 'PrettyXML' have been added to the download and store functions parameter.

The generateXml function have a $prettyXML parameter how default to false for api stability

**Comment by AbcAeffchen** [comment]
The XML files are meant to be uploaded to a bank or used in some other software.
You only need to prettify the output if a human is supposed to read it. Also a lot of XML readers can show the file formatted even though it is not. So this is nothing Sephpa should support and also nothing a dependency (DOMDocument) should be introduced.
