### ISSUE TITLE
 Remove HHVM from .travis.yml 

### ISSUE THREAD

**Issue by jmbIFR** [AbcAeffchen/Sephpa#24]
Travis support HHVM only on Ubuntu Trusty 14.04

https://docs.travis-ci.com/user/languages/php/#hhvm-versions-are-available-on-trusty-only

**Comment by AbcAeffchen** [comment]
At the moment Sephpa supports HHVM, so removing it from the tests is not a good option.
But probably the tests need to be updated such that the work on travis the way they are supposed to.

I will have a look into the tests as soon as possible.

**Comment by AbcAeffchen** [comment]
I allowed the hhvm builds to fail. I don't use hhvm so it is a little pain to maintain it and it got worse since travis seems to have some limitations on this. So it is on stand by and maybe the support gets just dropped with version 2.0
