### ISSUE TITLE
Locale

### ISSUE THREAD

**Issue by mweghorst** [AbcAeffchen/Sephpa#3]
The output of a SephpaCreditTransfer is invalid when working with a locale that uses commas as decimal_point for floats. `$amount = filter_var($amount, FILTER_VALIDATE_FLOAT, FILTER_FLAG_ALLOW_THOUSAND)` in SepaUtilities replaces my dots with comma's, causing instdAmt to be invalid.

Is there a way around this, besides something like `setlocale(LC_NUMERIC, 'en_US.UTF-8')`?

**Comment by AbcAeffchen** [comment]
Thanks for reporting this.

This is a bug in SepaUtilities. It is fixed in SepaUtilities 1.1.2 I just released.
