### ISSUE TITLE
Not possible to combine FRST and RCUR in one batch

### ISSUE THREAD

**Issue by ME-at-GH** [AbcAeffchen/Sephpa#31]
`$directDebitFile = new SephpaDirectDebit($initator_name 
                                                , $message_id
                                                , SephpaDirectDebit::SEPA_PAIN_008_001_02
                                                , $collectionData);`

Based on my analysis, I was not able to merge the two sepa types FRST and RCUR in one file. 

The $directDebitFile is expecting 4 parameters, and is dependent on $collectionData (array). 
The $collectionData expects seqTp. 
When you have two different seqTp, and defined two directDebitFile classes, only one seqTp is being saved in the xml batch.

The workaround is saving FRST and RCUR in two seperate files (works). Which is not user friendly and sensitive to errors.

I'm using the version 2.0, as this version supports DD 80102
Thanks a bunch for making this solution possible!

**Comment by AbcAeffchen** [comment]
Sorry for the very late response. This behavior was changed back a few month ago, so multiple different sequence types in one file should be possible again using the current master or verion 2.0 (tagged tomorrow).
