### ISSUE TITLE
addPayment() fehlt?!

### ISSUE THREAD

**Issue by soRailicious** [AbcAeffchen/Sephpa#35]
Hi,

ich habe eure Funktionalitäten bisher gerne genutzt... Nun habe ich in meinem Laravel - Projekt mal wieder einen "Zahllauf" starten wollen und nun fiel mir auf dass es scheinbar nicht mehr "addPayment()" gibt?! Die hatte ich in der DirectDebit Datei aber eigentlich immer angesprochen und nichts geändert... Was ist zutun? Bzw. was wurde hier verändert?

Über kurzes Feedback wäre ich dankbar.

$directDebitFile = new SephpaDirectDebit(.............)
...
$directDebitFile->addPayment([....])

daraus resultiert dann nachfolgender "Fehler"...

"Error
Call to undefined method AbcAeffchen\Sephpa\SephpaDirectDebit::addPayment()"

Grüße
Malte

**Comment by AbcAeffchen** [comment]
Hi Malte,

Das Interface wie du es beschreibst war glaube ich nur bei der 2.0 beta aktiv. Ich musste es wieder zum alten stand zurück ändern da so eine Funktionalität verloren ging, die doch benötigt wurde.

D.h. jetzt muss man wieder wie früher einen Zwischenschritt machen und eine PaymentCollection erstellen.

Wirf einen Blick ins [Wiki](https://github.com/AbcAeffchen/Sephpa/wiki/Direct-Debit-Example) für die Dokumentation und ein Beispiel.

Beste Grüße
Alex

**Comment by soRailicious** [comment]
Hi Alex,

danke für die super schnelle und hilfreiche Antwort. Top Arbeit dein Projekt!!!

Gruß
Malte
