### ISSUE TITLE
performance

### ISSUE THREAD

**Issue by ronnievisser** [AbcAeffchen/Sephpa#7]
I there anything known about this lib in case of huge PAIN files? let's say with 100k transactions in it?

**Comment by AbcAeffchen** [comment]
I have not tested Sephpa with that many transactions.
I recommend to turn off all checks and check your data on input time. This way you should only need thee time to generate the file it self. This time mainly depends on the speed of the SimpleXML library I use to generate XML files.

But I have to say that I have not tuned Sephpa to be as fast as possible. And I also not tested how fast it is and I also did no speed comparison to other SEPA libraries. But if you would make such a test, I would love to see the results and maybe we can improve the speed a little.

**Comment by ronnievisser** [comment]
Hi,

It's not mainly about speed but also about memory usage. Anything known about that?

Best regards,
Soccerama Support

**Comment by AbcAeffchen** [comment]
I just did a short test:

Using PHP 7 on a Athlon Phenom II X4 965 it took about 7.2 seconds and about 43.15 MB RAM to generate a file with one collection and 100.000 transactions while checkAndSanitize is turned off. The generated file has about 36 MB. If you turn checkAndSanitize on, it takes about 53 seconds and 100 MB RAM.

This is just a short test. This time gets bigger if you have to fetch your data from a database or read a file. For my test I just added 100.000 times the same transaction.

**Comment by ronnievisser** [comment]
Thanks, will do some tests myself tomorrow

**Comment by AbcAeffchen** [comment]
Did you had time to do some tests? I added my test script to the the development branch
 Sephpa/tests/SephpaTimeMemoryTest.php
