### ISSUE TITLE
abcaeffchen/sephpa 1.3.0 requires abcaeffchen/sepa-utilities ~1.1.0

### ISSUE THREAD

**Issue by thbergler** [AbcAeffchen/Sephpa#9]
In my composer.json I have got the following lines:

`        "abcaeffchen/sephpa": "~1.3",
        "abcaeffchen/sepa-utilities": "~1.2",`

I want to use the newest stable releases. But I get the following error:

abcaeffchen/sephpa 1.3.0 requires abcaeffchen/sepa-utilities ~1.1.0

When will a new release of sephpa, which supports sepa-utilities 1.2 ?

I don't want to use dev-master in my project.

**Comment by AbcAeffchen** [comment]
You can just remove the line where you require SepaUtilities 1.2. Sephpa 1.3 cannot use it anyway.

Sephpa 2.0 will hopefully released in the next weeks. I still have some work to do.
